import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface LandingCollectionItem extends PageCollectionItemBase {}
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface DocsCollectionItem extends PageCollectionItemBase {
    links?: {
    label: string;
    icon: string;
    to: string;
    target?: string;
    }[];
  }
  

  interface PageCollections {
    landing: LandingCollectionItem
    docs: DocsCollectionItem
  }

  interface Collections {
    landing: LandingCollectionItem
    docs: DocsCollectionItem
  }
}
