// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/raw/**:slug.md': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/raw/[...slug].md.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@4.1.2_@netlify+blobs@9_f516031233e580fab9a39a18d32067b6/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.0.0_magicast@0_b458d9adcb7bbe58612e1190b220c6bc/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.11_@unhea_731cc44203b8d07e639e852ded8c5ff5/node_modules/nuxt-og-image/dist/runtime/server/routes/font').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-site-config@3.2.8_h3@1_0c9b73547c7afb2d510d79e85f50eaa8/node_modules/nuxt-site-config/dist/runtime/server/routes/__site-config__/debug').default>>>>
    }
    '/__og-image__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.11_@unhea_731cc44203b8d07e639e852ded8c5ff5/node_modules/nuxt-og-image/dist/runtime/server/routes/debug.json').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.11_@unhea_731cc44203b8d07e639e852ded8c5ff5/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/__og-image__/static/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.11_@unhea_731cc44203b8d07e639e852ded8c5ff5/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/llms.txt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-llms@0.1.3_magicast@0.3.5/node_modules/nuxt-llms/dist/runtime/server/routes/llms.txt.get').default>>>>
    }
    '/llms-full.txt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-llms@0.1.3_magicast@0.3.5/node_modules/nuxt-llms/dist/runtime/server/routes/llms-full.txt.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/__nuxt_content/:collection/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.7.1_better-sqlite3@12.2.0_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/:collection/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.7.1_better-sqlite3@12.2.0_magicast@0.3.5/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@1.11.0_@netlify_aaa2e2584eca91dd023fef849109c2ee/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}