PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZODATA_V_PROP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZODATA_V_PROP-PROPERTY_NAME .
    FIELD ZODATA_V_PROP-ABAP_NAME .
    FIELD ZODATA_V_PROP-IS_KEY .
    FIELD ZODATA_V_PROP-COMPLEX_TYPE .
    FIELD ZODATA_V_PROP-SEARCH_HELP .
    FIELD ZODATA_V_PROP-AS_ETAG .
    FIELD ZODATA_V_PROP-NOT_FILTERABLE .
    FIELD ZODATA_V_PROP-NOT_EDITABLE .
    FIELD ZODATA_V_PROP-SORT_ORDER .
    FIELD ZODATA_V_PROP-FILTER_IN_FILTERBAR .
    FIELD ZODATA_V_PROP-MANDATORY_FILTER .
    FIELD ZODATA_V_PROP-NOT_VISIBLE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZODATA_V_PROP-PROPERTY_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
