PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZODATA_SEARCHHLP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZODATA_SEARCHHLP-ID .
    FIELD ZODATA_SEARCHHLP-TABNAME .
    FIELD ZODATA_SEARCHHLP-DESCRIPTION_FIELD .
    FIELD ZODATA_SEARCHHLP-DATA_ELEMENT .
    FIELD ZODATA_SEARCHHLP-WHERE_DATA_ELEMENT1 .
    FIELD ZODATA_SEARCHHLP-WHERE_VALUE1 .
    FIELD ZODATA_SEARCHHLP-WHERE_DATA_ELEMENT2 .
    FIELD ZODATA_SEARCHHLP-WHERE_VALUE2 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZODATA_SEARCHHLP-ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
