* VCL-Modifications
PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZODATA_V_ACTIONS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZODATA_V_ACTIONS-ACTION_NAME .
    FIELD ZODATA_V_ACTIONS-RETURNING_ENTITY .
    FIELD ZODATA_V_ACTIONS-HTTP_METHOD .
    FIELD ZODATA_V_ACTIONS-STRUCTURE_NAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZODATA_V_ACTIONS-ACTION_NAME .
    FIELD ZODATA_V_ACTIONS-RETURNING_ENTITY.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
*
PROCESS ON VALUE-REQUEST.
    FIELD  ZODATA_V_ACTIONS-RETURNING_ENTITY MODULE VCL_HELP_VALUES.
