*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 21.01.2021 at 13:27:53
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZODATA_V_NAV....................................*
FORM GET_DATA_ZODATA_V_NAV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZODATA_NAV WHERE
(VIM_WHERETAB) .
    CLEAR ZODATA_V_NAV .
ZODATA_V_NAV-MANDT =
ZODATA_NAV-MANDT .
ZODATA_V_NAV-NAMESPACE =
ZODATA_NAV-NAMESPACE .
ZODATA_V_NAV-NAV_PROP =
ZODATA_NAV-NAV_PROP .
ZODATA_V_NAV-FROM_ENTITY =
ZODATA_NAV-FROM_ENTITY .
ZODATA_V_NAV-TO_ENTITY =
ZODATA_NAV-TO_ENTITY .
ZODATA_V_NAV-CARDINALITY =
ZODATA_NAV-CARDINALITY .
<VIM_TOTAL_STRUC> = ZODATA_V_NAV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZODATA_V_NAV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZODATA_V_NAV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZODATA_V_NAV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZODATA_NAV WHERE
  NAMESPACE = ZODATA_V_NAV-NAMESPACE AND
  NAV_PROP = ZODATA_V_NAV-NAV_PROP .
    IF SY-SUBRC = 0.
    DELETE ZODATA_NAV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZODATA_NAV WHERE
  NAMESPACE = ZODATA_V_NAV-NAMESPACE AND
  NAV_PROP = ZODATA_V_NAV-NAV_PROP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZODATA_NAV.
    ENDIF.
ZODATA_NAV-MANDT =
ZODATA_V_NAV-MANDT .
ZODATA_NAV-NAMESPACE =
ZODATA_V_NAV-NAMESPACE .
ZODATA_NAV-NAV_PROP =
ZODATA_V_NAV-NAV_PROP .
ZODATA_NAV-FROM_ENTITY =
ZODATA_V_NAV-FROM_ENTITY .
ZODATA_NAV-TO_ENTITY =
ZODATA_V_NAV-TO_ENTITY .
ZODATA_NAV-CARDINALITY =
ZODATA_V_NAV-CARDINALITY .
    IF SY-SUBRC = 0.
    UPDATE ZODATA_NAV ##WARN_OK.
    ELSE.
    INSERT ZODATA_NAV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZODATA_V_NAV-UPD_FLAG,
STATUS_ZODATA_V_NAV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZODATA_V_NAV.
  SELECT SINGLE * FROM ZODATA_NAV WHERE
NAMESPACE = ZODATA_V_NAV-NAMESPACE AND
NAV_PROP = ZODATA_V_NAV-NAV_PROP .
ZODATA_V_NAV-MANDT =
ZODATA_NAV-MANDT .
ZODATA_V_NAV-NAMESPACE =
ZODATA_NAV-NAMESPACE .
ZODATA_V_NAV-NAV_PROP =
ZODATA_NAV-NAV_PROP .
ZODATA_V_NAV-FROM_ENTITY =
ZODATA_NAV-FROM_ENTITY .
ZODATA_V_NAV-TO_ENTITY =
ZODATA_NAV-TO_ENTITY .
ZODATA_V_NAV-CARDINALITY =
ZODATA_NAV-CARDINALITY .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZODATA_V_NAV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZODATA_V_NAV-NAMESPACE TO
ZODATA_NAV-NAMESPACE .
MOVE ZODATA_V_NAV-NAV_PROP TO
ZODATA_NAV-NAV_PROP .
MOVE ZODATA_V_NAV-MANDT TO
ZODATA_NAV-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZODATA_NAV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZODATA_NAV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZODATA_NAV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZODATA_V_PROP...................................*
FORM GET_DATA_ZODATA_V_PROP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZODATA_PROPERTY WHERE
(VIM_WHERETAB) .
    CLEAR ZODATA_V_PROP .
ZODATA_V_PROP-MANDT =
ZODATA_PROPERTY-MANDT .
ZODATA_V_PROP-NAMESPACE =
ZODATA_PROPERTY-NAMESPACE .
ZODATA_V_PROP-ENTITY_NAME =
ZODATA_PROPERTY-ENTITY_NAME .
ZODATA_V_PROP-PROPERTY_NAME =
ZODATA_PROPERTY-PROPERTY_NAME .
ZODATA_V_PROP-ABAP_NAME =
ZODATA_PROPERTY-ABAP_NAME .
ZODATA_V_PROP-IS_KEY =
ZODATA_PROPERTY-IS_KEY .
ZODATA_V_PROP-COMPLEX_TYPE =
ZODATA_PROPERTY-COMPLEX_TYPE .
ZODATA_V_PROP-SEARCH_HELP =
ZODATA_PROPERTY-SEARCH_HELP .
<VIM_TOTAL_STRUC> = ZODATA_V_PROP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZODATA_V_PROP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZODATA_V_PROP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZODATA_V_PROP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZODATA_PROPERTY WHERE
  NAMESPACE = ZODATA_V_PROP-NAMESPACE AND
  ENTITY_NAME = ZODATA_V_PROP-ENTITY_NAME AND
  PROPERTY_NAME = ZODATA_V_PROP-PROPERTY_NAME .
    IF SY-SUBRC = 0.
    DELETE ZODATA_PROPERTY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZODATA_PROPERTY WHERE
  NAMESPACE = ZODATA_V_PROP-NAMESPACE AND
  ENTITY_NAME = ZODATA_V_PROP-ENTITY_NAME AND
  PROPERTY_NAME = ZODATA_V_PROP-PROPERTY_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZODATA_PROPERTY.
    ENDIF.
ZODATA_PROPERTY-MANDT =
ZODATA_V_PROP-MANDT .
ZODATA_PROPERTY-NAMESPACE =
ZODATA_V_PROP-NAMESPACE .
ZODATA_PROPERTY-ENTITY_NAME =
ZODATA_V_PROP-ENTITY_NAME .
ZODATA_PROPERTY-PROPERTY_NAME =
ZODATA_V_PROP-PROPERTY_NAME .
ZODATA_PROPERTY-ABAP_NAME =
ZODATA_V_PROP-ABAP_NAME .
ZODATA_PROPERTY-IS_KEY =
ZODATA_V_PROP-IS_KEY .
ZODATA_PROPERTY-COMPLEX_TYPE =
ZODATA_V_PROP-COMPLEX_TYPE .
ZODATA_PROPERTY-SEARCH_HELP =
ZODATA_V_PROP-SEARCH_HELP .
    IF SY-SUBRC = 0.
    UPDATE ZODATA_PROPERTY ##WARN_OK.
    ELSE.
    INSERT ZODATA_PROPERTY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZODATA_V_PROP-UPD_FLAG,
STATUS_ZODATA_V_PROP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZODATA_V_PROP.
  SELECT SINGLE * FROM ZODATA_PROPERTY WHERE
NAMESPACE = ZODATA_V_PROP-NAMESPACE AND
ENTITY_NAME = ZODATA_V_PROP-ENTITY_NAME AND
PROPERTY_NAME = ZODATA_V_PROP-PROPERTY_NAME .
ZODATA_V_PROP-MANDT =
ZODATA_PROPERTY-MANDT .
ZODATA_V_PROP-NAMESPACE =
ZODATA_PROPERTY-NAMESPACE .
ZODATA_V_PROP-ENTITY_NAME =
ZODATA_PROPERTY-ENTITY_NAME .
ZODATA_V_PROP-PROPERTY_NAME =
ZODATA_PROPERTY-PROPERTY_NAME .
ZODATA_V_PROP-ABAP_NAME =
ZODATA_PROPERTY-ABAP_NAME .
ZODATA_V_PROP-IS_KEY =
ZODATA_PROPERTY-IS_KEY .
ZODATA_V_PROP-COMPLEX_TYPE =
ZODATA_PROPERTY-COMPLEX_TYPE .
ZODATA_V_PROP-SEARCH_HELP =
ZODATA_PROPERTY-SEARCH_HELP .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZODATA_V_PROP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZODATA_V_PROP-NAMESPACE TO
ZODATA_PROPERTY-NAMESPACE .
MOVE ZODATA_V_PROP-ENTITY_NAME TO
ZODATA_PROPERTY-ENTITY_NAME .
MOVE ZODATA_V_PROP-PROPERTY_NAME TO
ZODATA_PROPERTY-PROPERTY_NAME .
MOVE ZODATA_V_PROP-MANDT TO
ZODATA_PROPERTY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZODATA_PROPERTY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZODATA_PROPERTY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZODATA_PROPERTY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
