*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 14.12.2021 at 12:14:49
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZODATA_NAMESPACE................................*
DATA:  BEGIN OF STATUS_ZODATA_NAMESPACE              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZODATA_NAMESPACE              .
CONTROLS: TCTRL_ZODATA_NAMESPACE
            TYPE TABLEVIEW USING SCREEN '0008'.
*...processing: ZODATA_SEARCHHLP................................*
DATA:  BEGIN OF STATUS_ZODATA_SEARCHHLP              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZODATA_SEARCHHLP              .
CONTROLS: TCTRL_ZODATA_SEARCHHLP
            TYPE TABLEVIEW USING SCREEN '0004'.
*...processing: ZODATA_V_ACTIONS................................*
TABLES: ZODATA_V_ACTIONS, *ZODATA_V_ACTIONS. "view work areas
CONTROLS: TCTRL_ZODATA_V_ACTIONS
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZODATA_V_ACTIONS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZODATA_V_ACTIONS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZODATA_V_ACTIONS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_ACTIONS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_ACTIONS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZODATA_V_ACTIONS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_ACTIONS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_ACTIONS_TOTAL.

*...processing: ZODATA_V_ACTPARA................................*
TABLES: ZODATA_V_ACTPARA, *ZODATA_V_ACTPARA. "view work areas
CONTROLS: TCTRL_ZODATA_V_ACTPARA
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZODATA_V_ACTPARA. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZODATA_V_ACTPARA.
* Table for entries selected to show on screen
DATA: BEGIN OF ZODATA_V_ACTPARA_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_ACTPARA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_ACTPARA_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZODATA_V_ACTPARA_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_ACTPARA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_ACTPARA_TOTAL.

*...processing: ZODATA_V_ENTITY.................................*
TABLES: ZODATA_V_ENTITY, *ZODATA_V_ENTITY. "view work areas
CONTROLS: TCTRL_ZODATA_V_ENTITY
TYPE TABLEVIEW USING SCREEN '0009'.
DATA: BEGIN OF STATUS_ZODATA_V_ENTITY. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZODATA_V_ENTITY.
* Table for entries selected to show on screen
DATA: BEGIN OF ZODATA_V_ENTITY_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_ENTITY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_ENTITY_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZODATA_V_ENTITY_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_ENTITY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_ENTITY_TOTAL.

*...processing: ZODATA_V_NAV....................................*
TABLES: ZODATA_V_NAV, *ZODATA_V_NAV. "view work areas
CONTROLS: TCTRL_ZODATA_V_NAV
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZODATA_V_NAV. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZODATA_V_NAV.
* Table for entries selected to show on screen
DATA: BEGIN OF ZODATA_V_NAV_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_NAV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_NAV_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZODATA_V_NAV_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_NAV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_NAV_TOTAL.

*...processing: ZODATA_V_PROP...................................*
TABLES: ZODATA_V_PROP, *ZODATA_V_PROP. "view work areas
CONTROLS: TCTRL_ZODATA_V_PROP
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZODATA_V_PROP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZODATA_V_PROP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZODATA_V_PROP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_PROP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_PROP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZODATA_V_PROP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_PROP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_PROP_TOTAL.

*...processing: ZODATA_V_PROPTXT................................*
TABLES: ZODATA_V_PROPTXT, *ZODATA_V_PROPTXT. "view work areas
CONTROLS: TCTRL_ZODATA_V_PROPTXT
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZODATA_V_PROPTXT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZODATA_V_PROPTXT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZODATA_V_PROPTXT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_PROPTXT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_PROPTXT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZODATA_V_PROPTXT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZODATA_V_PROPTXT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZODATA_V_PROPTXT_TOTAL.

*.........table declarations:.................................*
TABLES: *ZODATA_NAMESPACE              .
TABLES: *ZODATA_SEARCHHLP              .
TABLES: ZODATA_ACTIONS                 .
TABLES: ZODATA_ACT_PARAM               .
TABLES: ZODATA_ENTITY                  .
TABLES: ZODATA_NAMESPACE               .
TABLES: ZODATA_NAV                     .
TABLES: ZODATA_PROPERTY                .
TABLES: ZODATA_PROP_TXTS               .
TABLES: ZODATA_SEARCHHLP               .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
