PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZODATA_V_ENTITY CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZODATA_V_ENTITY-ENTITY_NAME .
    FIELD ZODATA_V_ENTITY-CLASS_NAME .
    FIELD ZODATA_V_ENTITY-STRUCTURE .
    FIELD ZODATA_V_ENTITY-IS_COMPLEX .
    FIELD ZODATA_V_ENTITY-DEEP_ENTITY_STRUCTURE .
    FIELD ZODATA_V_ENTITY-IS_MEDIA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZODATA_V_ENTITY-ENTITY_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
